CREATE DATABASE TARIFA_DREAMS CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE Cliente IF NOT EXISTS(
dni CHAR(9) PRIMARY KEY,
nombre VARCHAR(30) NULL,
apellido_1 VARCHAR(30) NULL,
apellido_2 VARCHAR(30) NULL,
correo VARCHAR(50) NOT NULL,
direccion VARCHAR(60) NULL,
localidad VARCHAR(25) NULL,
telefono CHAR(13) NULL,
codigo_acceso CHAR(7) NOT NULL
);

CREATE TABLE habitacion IF NOT EXISTS(
id SMALLINT UNSIGNED PRIMARY KEY,
nombre ENUM("Individual", "Doble", "Triple") NOT NULL,
numero_camas TINYINT UNSIGNED NOT NULL,
max_personas TINYINT UNSIGNED NOT NULL,
precio TINYINT UNSIGNED NOT NULL,
descripcion TEXT NULL
);

CREATE TABLE Reserva IF NOT EXISTS(
id CHAR()

)